### ISSUE TITLE
 I cannot download or view any of the files

### ISSUE THREAD

**Issue by Getafix17** [PetoiCamp/NonCodeFiles#3]
Hi I have been trying to download the stl files, I get 'Unable to render rich display' error and I cannot download any of the files.
Kindly let me know if the files are not available or if they are corrupted.

**Comment by borntoleave** [comment]
What browser are you using? I just checked and the files are available.

**Comment by Getafix17** [comment]
I am using chrome.

**Comment by Getafix17** [comment]
Same problem with Microsoft Edge...

**Comment by Getafix17** [comment]
Great Thanks, I can download it as a zip.
